### ISSUE TITLE
Percentage comparison graph?

### ISSUE THREAD

**Issue by coreyfarrell** [cheapsteak/npmcharts.com#102]
I'm not sure if this is practical for your page but I'd love to see a relative comparison graph.  For example https://npmcharts.com/compare/process-on-spawn,nyc?interval=1&start=30 shows downloads for process-on-spawn and nyc in absolute values.  nyc 15.0.0 is currently the only source of downloads for process-on-spawn so if process-on-spawn gets 25,000 downloads and nyc gets 200,000 then 12.5% of users have upgraded to nyc 15.0.0.  Really for the purpose of this graph I'm not actually interested in the ups and downs of nyc total downloads.

Feel free to close this if impractical or if you think it is too niche.

**Comment by cheapsteak** [comment]
Sorry for the slow response!  

This sounds like it might be similar to https://github.com/cheapsteak/npmcharts.com/issues/37 (I wanted to adjust for "inflation" by using lodash as the reference). Although apologies that I might not get around to implementing this anytime soon :( 

Code-wise shouldn't be too difficult, but have trouble thinking through how to puzzle that into the UI 🤔
