### ISSUE TITLE
oembed url starts with http://

### ISSUE THREAD

**Issue by Leko** [cheapsteak/npmcharts.com#114]
Hi there,
I found a problem regarding oEmbed URL.

URL: https://npmcharts.com/compare/express,koa,nest,@adonisjs/framework,connect,@nestjs/core,fastify,hapi,loopback

```
<link title="Compare npm downloads for express, koa, nest, @adonisjs/framework, connect, @nestjs/core, fastify, hapi and loopback - npmcharts 📈" rel="alternate" type="application/json+oembed" href="https://npmcharts.com/oembed?url=http%3A%2F%2Fnpmcharts.com%2Fcompare%2Fexpress%2Ckoa%2Cnest%2C%40adonisjs%2Fframework%2Cconnect%2C%40nestjs%2Fcore%2Cfastify%2Chapi%2Cloopback&format=json">
```

## Actual behavior

oEmbed URL starts with http://

## Expected behavior 

It should start with https://

I think the problem is caused by this line.
https://github.com/cheapsteak/npmcharts.com/blob/master/packages/server/routes/index.js#L19

**Comment by cheapsteak** [comment]
yup looks like that was it! thank you so much 🙏 🙏 
(I still don't quite understand why that's the case, but hardcoded the protocol to https for now so the behaviour should now at least be correct)


curious if you can share where you're looking to use the oembed?

**Comment by Leko** [comment]
@cheapsteak Thank you for your quick action!
I'm using oEmbed of npmcharts as an embeddable element in my blog. I created a gatsby plugin and use it for embedding discoverable oEmbed.

This is my article to explain what is oEmbed and my Gatsby plugin (Japanese)
> &mdash; [Gatsbyの記事にoEmbed準拠のコンテンツを埋め込めるようにした | WEB EGG](https://blog.leko.jp/post/gatsby-remark-discoverable-oembed/)
