### ISSUE TITLE
Add storybooks for graph using log scale

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#121]
There are currently storybooks using linear scale for intervals 1, 7, 30
https://github.com/cheapsteak/npmcharts.com/blob/master/packages/frontend/src/graph/graph.stories.js

Log scale could use some stories as well (this is the one that breaks when minifying with mangle/compression on)

**Comment by JonLim** [comment]
Please assign to me! I'll explore and try to make some progress with this.

**Comment by cheapsteak** [comment]
closed by https://github.com/cheapsteak/npmcharts.com/pull/126
