### ISSUE TITLE
Upgrade puppeteer to v5

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#123]
The server uses puppeteer to generate screenshots

It currently uses [puppeteer@2.1.1](https://github.com/cheapsteak/npmcharts.com/blob/7ed63078471a779f8049fe560bceae897553fad7/packages/server/package.json#L21)

The latest version is currently [5.3.1](https://www.npmjs.com/package/puppeteer)

Would be useful to upgrade and see if anything's broken (hoping it might just work)

To test, run the server by `cd package/server && npm start`, then navigate to `http://localhost:3896/chart-image/vue.png`, wait for it to load (takes a while), and see if a chart comes back. If yes, we're good to go; if not, might need to do some debugging

**Comment by Aditya-ds-1806** [comment]
I would like to work on this. Can u assign it to me?

**Comment by cheapsteak** [comment]
@Aditya-ds-1806 yup! thank you 🙏

**Comment by Aditya-ds-1806** [comment]
Hey, Im having trouble setting up the project on my system. Here is what i did:
1. cd packages/server
2. npm i
3. npm start

It starts on local sevrer but in browser nothing loads, there are some webpack errors in console saying some css files were notfound

**Comment by Aditya-ds-1806** [comment]
No issues, I figured it out!

**Comment by Aditya-ds-1806** [comment]
Good news. No errors!
