### ISSUE TITLE
Figure out why log scale charts break when Terser's `mangle: true`; then turn mangle on

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#124]
Had to [turn off `mangle`](https://github.com/cheapsteak/npmcharts.com/blob/7ed63078471a779f8049fe560bceae897553fad7/packages/frontend/webpack.config.js#L100) because `mangle: true` was causing graphs in log scale to bork:

![image](https://user-images.githubusercontent.com/743976/95220296-4fe00d00-07c4-11eb-93b9-688c6fc62ae5.png)

Graphs where the y is 0 at any point end up sticking to the top of the chart rather than the bottom when mangle is on
Baffling

If we can turn mangle on again, we could save a couple hundred kbs from the bundle (300kb, I think)

**Comment by JonLim** [comment]
Feel free to assign this to me, as well. Have a PR coming!
