### ISSUE TITLE
Add instructions to set up the project locally

### ISSUE THREAD

**Issue by Aditya-ds-1806** [cheapsteak/npmcharts.com#129]
I myself faced a few problems with (npm and yarn) while setting up the project locally. This will save other's time and will help them get started easily. I would like to take this issue and add a section in the readme.md file.

**Comment by cheapsteak** [comment]
sounds great! @Aditya-ds-1806

**Comment by Aditya-ds-1806** [comment]
Can u assign it to me? I would be happy to work

**Comment by Aditya-ds-1806** [comment]
Thanks, will start soon, it's very late where I live.

**Comment by cheapsteak** [comment]
no rush! 🙏 sleep well
