### ISSUE TITLE
y-axis guides and labels look weird in log scale

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#130]
The y-axis guides and labels in log-scale currently remains the same as linear scale,  (100, 200, 300, ...1000, 1100, 1200 etc)  

This makes them look rather weird and squished  

It should probably be changed to 100,   1000,   10,000,   100,000   1,000,000  etc

![image](https://user-images.githubusercontent.com/743976/95277784-a0835480-081c-11eb-8139-b7c8bd7d89d1.png)

https://github.com/cheapsteak/npmcharts.com/blob/master/packages/frontend/src/graph/graph.js is probably a good place to start

**Comment by Xiaohanxu1996** [comment]
Hi, I will take a look on this issue.

**Comment by cheapsteak** [comment]
@Xiaohanxu1996 much appreciated 🙏
