### ISSUE TITLE
Replace "Crafted in 🍁 by Chang Wang" since that's no longer wholly true

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#139]
Maybe we can start with a simple JSON file of contributors that the app reads
```js
{
  name: "Chang Wang",
  location: "🍁"
},
{
  name: "Borewit",
  location: "🇳🇱",
},
{
  name: "Jon Lim",
  location: "🗽"
},
//...
```

and randomize which one shows up on page load

relevant lines of code currently - https://github.com/cheapsteak/npmcharts.com/blob/c7dfdfa0a793b1780fcf81b43e6625c2daa10277/packages/frontend/src/home/home.html#L217-L231

way way way down the line, maybe some kind of bot similar to CLA bots that ask for this info as part of the PR process

**Comment by vividh** [comment]
I would like to claim this issue.

**Comment by cheapsteak** [comment]
Would appreciate it!

**Comment by vividh** [comment]
Thanks!

I would like to discuss an alternative option as well:
Instead of picking one random contributor from the list, how about cycling through the list of contributors one by one, every 10 or 15 seconds, with a fade in / fade out animation?

Let me know what you think about this?

**Comment by vividh** [comment]
Also, can you provide the list of contributors to use? I have the following as of now. Please provide the profile link for each contributor as well.

```json
[
  {
    "name": "Chang Wang",
    "location": "🍁",
    "link": "https://twitter.com/CheapSteak"
  },
  {
    "name": "Borewit",
    "location": "🇳🇱",
    "link": ""
  },
  {
    "name": "Jon Lim",
    "location": "🗽",
    "link": ""
  }
]
```

**Comment by cheapsteak** [comment]
> Thanks!
> 
> I would like to discuss an alternative option as well:
> Instead of picking one random contributor from the list, how about cycling through the list of contributors one by one, every 10 or 15 seconds, with a fade in / fade out animation?
> 
> Let me know what you think about this?

I worry that animations would be distracting / annoying for visitors, would prefer to keep the focus on the stats :) 

Although could have it cycle through on click?

> "link": "https://twitter.com/CheapSteak"

Please omit the link field, I want to avoid getting into a position of needing to define what's acceptable to link out to 🙏 

> provide the list of contributors to use

Could you please use this list (and also do include yourself!)
https://github.com/cheapsteak/npmcharts.com/graphs/contributors
And leave everyone's "location" field blank for now, don't really want to assume, can use 🌍 as the default 

Thanks you for being so thorough 🙏 🙇

**Comment by vividh** [comment]
> I worry that animations would be distracting / annoying for visitors, would prefer to keep the focus on the stats :)

Haha yeah, I was also thinking the same after suggesting it 😄 .

> 
> Although could have it cycle through on click?

Yup, will make this happen.

> 
> > "link": "https://twitter.com/CheapSteak"
> 
> Please omit the link field, I want to avoid getting into a position of needing to define what's acceptable to link out to 🙏

Makes sense.

**Comment by vividh** [comment]
Hey @cheapsteak, made the changes in https://github.com/cheapsteak/npmcharts.com/pull/140. Do take a look and let me know if anything should be changed.
