### ISSUE TITLE
npmcharts.com down

### ISSUE THREAD

**Issue by Borewit** [cheapsteak/npmcharts.com#143]
[npmcharts.com](https://npmcharts.com/compare/music-metadata,jsmediatags,musicmetadata,node-id3,music-metadata-browser,id3-parser,mp4-parser,parse-audio-metadata,music-tags,id3,read-id3-tags,stream-id3,wav-file-info,audio-metadata,mutag?start=250) seems to be down. I hope its not permanent.

![npmcharts com_compare_music-metadata,jsmediatags,musicmetadata,node-id3,music-metadata-browser,id3-parser,mp4-parser,parse-audio-metadata,music-tags,id3,read-id3](https://user-images.githubusercontent.com/23255260/99496687-12e76880-2975-11eb-9142-ca096ade07c4.png)

**Comment by cheapsteak** [comment]
ack, apologies and thanks for the heads up!
fixed in https://github.com/cheapsteak/npmcharts.com/commit/d2f1ad94361c14530d76a2d4deff746ba7ddad3b

**Comment by cheapsteak** [comment]
Added a status page with some pages to monitor https://status.npmcharts.com/ :)
