### ISSUE TITLE
"This website npmcharts.com/ is currently offline"

### ISSUE THREAD

**Issue by janpio** [cheapsteak/npmcharts.com#192]
Seems the origin server is currently offline, and Cloudflare is providing a static cached version only.

![image](https://github.com/cheapsteak/npmcharts.com/assets/183673/90f72476-4e0f-4634-9668-587df48ad526)

**Comment by cheapsteak** [comment]
Thanks so much for the heads up! 🙏🙏 

Was on vacation for a week and looks like my digital ocean droplet ran out of space 😓 

Fixed for now

Going to migrate this off digital ocean long term

**Comment by janpio** [comment]
Awesome, thanks!
