### ISSUE TITLE
npmcharts.com not reachable

### ISSUE THREAD

**Issue by Borewit** [cheapsteak/npmcharts.com#194]
My dear friend,

Seems like [npmcharts.com](https://npmcharts.com/) is having difficulties, I hope there is way to recover this great service.

![image](https://github.com/user-attachments/assets/b1a65b76-9af1-4be5-8133-e98eea9bfee2)

**Comment by cheapsteak** [comment]
thanks so much for the heads up again

looking in

**Comment by cheapsteak** [comment]
backend's up again

frontend's still having issues, start range is earlier by a day somehow, not reproing locally :\

**Comment by cheapsteak** [comment]
ok, all fixed now

really appreciate the heads up 🙏 

the machine rebooted and didn't start up right (using pm2 but something was misconfigured)

I really need to migrate out of digitalocean and to vercel or something, I'm not a great sysadmin XD
