### ISSUE TITLE
X-axis not offsetting at 0 with a single data point

### ISSUE THREAD

**Issue by Borewit** [cheapsteak/npmcharts.com#195]
There is a small bug in the x-axis offset, when, presumably, only a single data point is available:

![image](https://github.com/user-attachments/assets/692db1aa-41ba-47a4-bc3c-652210ea302a)

**Comment by cheapsteak** [comment]
thanks for reporting!

fixed by https://github.com/cheapsteak/npmcharts.com/commit/3afe0a5fcb2b27d9eb7646eaaddc216d524ad4e3

(a `||` should have been a `??` 😄 )

**Comment by Borewit** [comment]
Much better!

![image](https://github.com/user-attachments/assets/ef672c67-6614-45ab-abfd-021a648b9b10)
