### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#33]
https://www.google.com/webmasters/tools/rich-cards?hl=en&siteUrl=http://npmcharts.com/

customize meta descriptions in server rendered html

Title
Compare download trends of (npm packages|for $packages) - npmcharts.com 📈
Description
Guide your decisions on which npm packages to choose and which to avoid by comparing download counts charted over time.

**Comment by JonLim** [comment]
Is this still an outstanding issue? I see that there is a `<meta name="description"` tag, as well as a `<title>` tag that matches the text in the original issue.

If there are other SEO-related bits to add, let me know!

**Comment by cheapsteak** [comment]
oo oops you're right this is issue is outdated 
closing 🙏
