### ISSUE TITLE
Handle npm api fetch errors

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#41]
Currently shows a blank screen when npm api requests error out

Fetch API cannot load https://api.npmjs.org/downloads/range/2016-08-18:2017-08-18/glamor,aphrodite,radium,glamorous,styled-components.

![image](https://user-images.githubusercontent.com/743976/29465078-f3d0d430-8405-11e7-9c2d-72da2da42483.png)

Should show a failwhale or something

**Comment by anatdagan** [comment]
Hi,
If this issue is still relevant, please assign it to me

**Comment by cheapsteak** [comment]
@anatdagan apologies this was indeed already addressed, thanks for checking
closing 🙏
