### ISSUE TITLE
add prefetch tag for api requests

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#43]

**Comment by kenrick95** [comment]
Hi, just to let you know that I'm working a bit on this issue. I thought I could send a PR in one sitting but apparently not. So far, my progress is such: prefetch tag is easy to add, determining which packages to request for is easy too, but determining the start/end dates for the API request seem a bit complicated. So I'm currently reading the codes trying to understand `getPackagesDownloadsOverPeriod` on how to extract the start/end dates out as a separate function :v:

**Comment by cheapsteak** [comment]
thanks for the heads up!
