### ISSUE TITLE
Add option to show data by month (or year) instead of showing by day

### ISSUE THREAD

**Issue by lmcarreiro** [cheapsteak/npmcharts.com#54]
When we wanna see a big time window, it shows too much points on the chart. It would be nice to have an option to show only one point by month.
Maybe after a few years, we would need to see one point by year too.

**Comment by cheapsteak** [comment]
Would having [an option to show moving averages](https://github.com/cheapsteak/npmcharts.com/issues/5) solve the same problem? 
Might have some time to work on it this holiday season, but would love to have some help if anyone is able :D

**Comment by lmcarreiro** [comment]
> Would having an option to show moving averages solve the same problem?
I think so.
