### ISSUE TITLE
Allow exporting image (without screen cap)

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#55]
Currently have to go into minimal mode and screen cap

Should have a single button that exports the current view

**Comment by kenrick95** [comment]
This is technically possible by introducing a button to link to the image link generated for og:image right?

**Comment by cheapsteak** [comment]
@kenrick95 that wouldn't quite export the current view, would prefer if it exports exactly what the user is seeing :)  

This looks promising - https://www.npmjs.com/package/html-to-image , specifically the `toBlob`

```
htmlToImage.toBlob(document.getElementById('my-node'))
  .then(function (blob) {
    fileSaver.saveAs(blob, 'my-node.png');
  });
```

**Comment by kenrick95** [comment]
Cool! Let me try this out 😁

**Comment by kenrick95** [comment]
Okay I tried that `html-to-image` package, and it seems like it doesn't generate a very good image.

![npmcharts-chart](https://user-images.githubusercontent.com/3090380/95671162-1ba28d00-0bc6-11eb-9c88-c0dfa8559c31.png)


May be related to [this bug report](https://github.com/bubkoo/html-to-image/issues/56)

> [..] it doesn't seem to be processing CSS classes for SVG elements [..]

**Comment by cheapsteak** [comment]
@kenrick95 thanks so much for investigating!
