### ISSUE TITLE
Tooltip numbers are shifted by one item

### ISSUE THREAD

**Issue by hudochenkov** [cheapsteak/npmcharts.com#74]
When hover over a dot number is shown for a previous dot. https://npmcharts.com/compare/react

![screen shot 2018-08-12 at 10 58 21](https://user-images.githubusercontent.com/654597/44000368-ef6f785e-9e1e-11e8-8152-440ba7149e1a.png)
![screen shot 2018-08-12 at 10 58 27](https://user-images.githubusercontent.com/654597/44000369-ef8985aa-9e1e-11e8-93e2-edde4f0b3881.png)

**Comment by cheapsteak** [comment]
Apologies I've neglected this a bit 🙇 
I believe this has since been fixed!

**Comment by hudochenkov** [comment]
Looks like it was :) Thank you for this tool! :)
