### ISSUE TITLE
Date label is incorrect for monthly

### ISSUE THREAD

**Issue by coreyfarrell** [cheapsteak/npmcharts.com#83]
https://npmcharts.com/compare/node-sass,less,stylus?interval=30

This currently says `February 5th, 2019 - 11th` for the most current period (at the top-left of the graph).  The ending date is incorrect, I think it should say `February 5th, 2019 - March 6th`.

**Comment by cheapsteak** [comment]
Oh shoot, you're right! thanks for reporting, will fix this soon

**Comment by cheapsteak** [comment]
Should be fixed! Thanks again for filing the bug
![image](https://user-images.githubusercontent.com/743976/53929300-47a97400-405b-11e9-90f8-5dce8ffc0468.png)

Closing! 👕 👖

**Comment by coreyfarrell** [comment]
Should this be through March 7th or March 6th?  I think you might need to subtract 1 from the ending date anytime the interval is greater than 1.  This report doesn't actually contain any data from March 7th.  This applies to weekly and all custom intervals > 1 (the interval=1 displays a single date thus avoiding this issue).

**Comment by cheapsteak** [comment]
Oh yikes, you're right!
Thanks so much for the thoroughness

**Comment by cheapsteak** [comment]
![image](https://user-images.githubusercontent.com/743976/53930239-9dcbe680-405e-11e9-909e-cce2fd83fc35.png)

3rd time's the charm 😅 
Thanks again going through the trouble of reporting the issue and following up when I fudged the numbers, it's incredibly appreciated 🙏 	🙏 

Closing again 🤞

**Comment by coreyfarrell** [comment]
Looks great now!  Awesome page BTW!
