### ISSUE TITLE
Period argument get lost if a new package is added

### ISSUE THREAD

**Issue by Borewit** [cheapsteak/npmcharts.com#86]
Initial URL, showing "musicbrainz-api" chart over a period of the past 100 days:

[/compare/node-acousticbrainz?start=100](https://npmcharts.com/compare/musicbrainz-api?start=100)

URL after adding "musicbrainz-client":

[/compare/musicbrainz-api,musicbrainz-client](https://npmcharts.com/compare/musicbrainz-api,musicbrainz-client)

We lost the: "?start=100"

Related: 
* #81 Implemented ability to retrieve charts over different & longer periods

**Comment by cheapsteak** [comment]
Thanks for the heads up! This should fix that - https://github.com/cheapsteak/npmcharts.com/commit/e761a92239a8646bc10aae26706b4e265798b345 

Deploying now

**Comment by cheapsteak** [comment]
Looks like it's fixed! Closing, let me know if you still hit any issues :) 
Thanks again for opening the issue 🙏

**Comment by Borewit** [comment]
Thanks for fixing it @cheapsteak.
I still love your app, on many of my repo's I link the nr-of-downloads-shield to it.

For example [![npm downloads](http://img.shields.io/npm/dm/musicbrainz-api.svg)](https://npmcharts.com/compare/musicbrainz-api) as found on [musicbrainz-api](https://github.com/Borewit/musicbrainz-api).

**Comment by cheapsteak** [comment]
❤️ appreciate your support!
