### ISSUE TITLE
npmcharts.netlify.com revoked certificate

### ISSUE THREAD

**Issue by coreyfarrell** [cheapsteak/npmcharts.com#87]
I get a blank page when I try loading npmcharts.com.  I did a little digging and found that https://npmcharts.netlify.com/static/app.bundle.js is failing to load.  When I try loading that script directly I get `An error occurred during a connection to npmcharts.netlify.com. Peer’s Certificate has been revoked. Error code: SEC_ERROR_REVOKED_CERTIFICATE`.

I get this error in Firefox 67.0.4 under Fedora 30.  This looks to be an OCSP issue.  Under Firefox Preferences at the very end of 'Privacy & Security' I disabled `Query OCSP responder servers to confirm the current validity of certificates` - this suppressed the error.

**Comment by cheapsteak** [comment]
Oh shoot, verified on my Mac's firefox, showing the same thing  
It looks like something on Netlify is not working correctly   
I'll wait a while to see if Netlify can resolve this themselves or if I need to have a backup bundle  
Thanks for the report!

**Comment by coreyfarrell** [comment]
This appears to be resolved, thanks for looking into this and for the link!
