### ISSUE TITLE
Rolling averages chart

### ISSUE THREAD

**Issue by coreyfarrell** [cheapsteak/npmcharts.com#88]
Is it possible to view a rolling monthly chart?  Currently the monthly chart shows a data point for the past 30 days, another data point for the 30 days before that, etc.  I'd like to see a "daily" graph where each data point is the total of the previous 30 days.  Sept 16 - Oct 15 would be the latest data point, Sept 15 - Oct 14 before that, Sept 14 - Oct 13 before that, etc.

Edit: I'm unsure if each data-point should be the daily average of the date range or the total downloads.  Either would give the ability to see a smoothed daily chart.

**Comment by cheapsteak** [comment]
Would love to add that! I believe https://github.com/cheapsteak/npmcharts.com/issues/5 might track the same desire. No time yet, would be great if anyone else wanted to tackle this

**Comment by cheapsteak** [comment]
we seem to need this a bit less now that we have weekly downloads?
