### ISSUE TITLE
No response accessing multiple scoped packages via URL

### ISSUE THREAD

**Issue by Borewit** [cheapsteak/npmcharts.com#98]
This works:
https://npmcharts.com/compare/@music-metadata/s3?start=300

This does not work:
https://npmcharts.com/compare/@music-metadata/s3,@tokenizer/range?start=300

**Comment by cheapsteak** [comment]
Thanks for the heads up! looks like the pattern matcher I was using doesn't handle slashes very well (thinks its part of a separate path). Gonna rip it out :)

**Comment by Borewit** [comment]
Okay, great, I didn't had the opportunity yet to look into it myself.

Thanks @cheapsteak, let me know if I need you need help.

**Comment by cheapsteak** [comment]
Just deployed this, https://github.com/cheapsteak/npmcharts.com/commit/0d4be840321211b9b000cf1b6ce1d58a4bc3e964 
should be working now!

**Comment by Borewit** [comment]
Lightning fast, cheers!
